spring:
  profiles:
    active:
    - local

---

spring:
  profiles:
  - local
         
  datasource:
    url: jdbc:mysql://3.38.87.14:3306/jeon?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wjsqudwns1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB        
      enabled: true      
   
  devtools:
    livereload:
      enabled: true
    restart:      log-condition-evaluation-delta: false
      
server:
  port: 9000 
  tomcat:    uri-encoding: UTF-8
    
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
       
    session: 
      timeout: 7200
  error:
      whitelabel:
        enabled: false

logging:
  config: classpath:logback-spring.xml  

mybatis:
  type-aliases-package: com.lcom_test.example.domain
  mapper-locations: mapper/**/*.xml
 